### ISSUE TITLE
Deprecation warning in CRS - change of axis order.

### ISSUE THREAD

**Issue by ga-ellis** [GeoscienceAustralia/wagl#352] opened 2021-06-25 00:12 UTC
`"/build/conda/lib/python3.8/site-packages/pyproj/crs/crs.py:306: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6\n"`

May need a dependency upgrade.

**Comment by uchchwhash** [comment] 2021-07-05 03:26
I think I might know why. I think it is trying to create the CRSs from the attributes stored in the ancillary `.h5` files. As such, this is not a bug in `wagl` itself. Closing.

**Closed as completed by uchchwhash** 2021-07-05 03:26 UTC
